saleor/dashboard/page/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.page_list, name='page-list'),
    url(r'^add/$', views.page_add, name='page-add'),
    url(r'^(?P<pk>[0-9]+)/$', views.page_details, name='page-details'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.page_update, name='page-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.page_delete, name='page-delete'),

    url(r'^(?P<pk>[0-9]+)/translations/(?P<translation_pk>[0-9]+)$',
        views.page_translation_details, name='page-translation-details'),
    url(r'^add/page/translation/$',
        views.page_translation_create, name='page-translation-add'),
    url(r'^(?P<pk>[0-9]+)/translation/add/$',
        views.page_translation_create, name='page-translation-add'),
    url(r'^(?P<pk>[0-9]+)/translations/(?P<translation_pk>[0-9]+)/edit/$',
        views.page_translation_edit, name='page-translation-update'),
    url(r'^(?P<pk>[0-9]+)/translations/(?P<translation_pk>[0-9]+)/delete/$',
        views.page_translation_delete, name='page-translation-delete')
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import (
    cart_urlpatterns as cart_urls, checkout_urlpatterns as checkout_urls)
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.views import GraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

from django.views.generic import TemplateView

handler404 = 'saleor.core.views.handle_404'

non_translatable_urlpatterns = [
    url(r'^dashboard/',
        include((dashboard_urls, 'dashboard'), namespace='dashboard')),
    url(r'^graphql/', csrf_exempt(GraphQLView.as_view(
        schema=schema)), name='api'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^i18n/$', set_language, name='set_language'),
    url('', include('social_django.urls', namespace='social'))]

translatable_urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^cart/', include((cart_urls, 'cart'), namespace='cart')),
    url(r'^checkout/',
        include((checkout_urls, 'checkout'), namespace='checkout')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^order/', include((order_urls, 'order'), namespace='order')),
    url(r'^page/', include((page_urls, 'page'), namespace='page')),
    url(r'^products/',
        include((product_urls, 'product'), namespace='product')),
    url(r'^account/',
        include((account_urls, 'account'), namespace='account')),
    url(r'^feeds/',
        include((feed_urls, 'data_feeds'), namespace='data_feeds')),
    url(r'^search/', include((search_urls, 'search'), namespace='search'))]

urlpatterns = non_translatable_urlpatterns + i18n_patterns(
    *translatable_urlpatterns)

urlpatterns += [
    url(r'^robots\.txt$', TemplateView.as_view(template_name="robots/robots.txt", content_type='text/plain')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        # static files (images, css, javascript, etc.)
        url(r'^static/(?P<path>.*)$', serve)] + static(
            '/media/', document_root=settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [
        url(r'^silk/', include('silk.urls', namespace='silk'))]

templates/dashboard/page/page_translation/detail.html
{% extends "dashboard/base.html" %}

{% load i18n %}
{% load price from taxed_prices %}
{% load static %}
{% load status %}

{% block title %}
  {{ translation }} - {{ block.super }}
{% endblock %}

{% block body_class %}body-pages{% endblock %}

{% block menu_pages_class %}active{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:page-list" %}" class="breadcrumb">
        {% trans "pages" context "page form breadcrumbs" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:page-list" %}">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li class="hide-on-med-and-down">
      <a href="{% url "dashboard:page-translation-details" pk=page.pk translation_pk=translation.pk %}" class="breadcrumbs--ellipsed-item">
        {{ page }}
      </a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {{ translation }}
      </span>
    </li>
  </ul>
{% endblock %}

{% block header_extra %}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col m12">
      <div class="card">
        <div class="card-content">
{#          <div style="overflow: auto; width: 100%; display: inline-block">#}
          <div>
          <table class="bordered responsive data-table">
            <tbody>
            <tr>
              <td><b>{% trans "Language" context "Dashboard action" %}</b></td>
              <td><b>{{ translation.language_code }}</b></td>
            </tr>
            <tr>
              <td>{% trans "Title" context "Dashboard action" %}</td>
              <td style="white-space: pre-wrap">{{ translation.title }}</td>
            </tr>
            <tr>
              <td>{% trans "Seo Title" context "Dashboard action" %}</td>
              <td style="white-space: pre-wrap">{{ translation.seo_title }}</td>
            </tr>
            <tr>
              <td>{% trans "Description" context "Dashboard action" %}</td>
              <td style="white-space: pre-wrap">{{ translation.content }}</td>
            </tr>
            <tr>
              <td>{% trans "Seo Description" context "Dashboard action" %}</td>
              <td style="white-space: pre-wrap">{{ translation.seo_description }}</td>
            </tr>
            </tbody>
          </table>
          </div>
        <div class="card-action">
          <a class="btn-flat waves-effect" href="{% url 'dashboard:page-translation-update' pk=page.pk translation_pk=translation.pk %}">
            {% trans "Edit" context "Dashboard action" %}
          </a>
          <a href="#base-modal" class="btn-flat waves-effect modal-trigger-custom" data-href="{% url 'dashboard:page-translation-delete' pk=page.pk translation_pk=translation.pk %}">
            {% trans "Remove" context "Dashboard action" %}
          </a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/dashboard/page/page_translation/form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load static %}

{% block title %}
  {{ translation }} - {{ block.super }}
{% endblock %}

{% block body_class %}body-pages{% endblock %}

{% block menu_pages_class %}active{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:page-list" %}" class="breadcrumb">
        {% trans "pages" context "Dashboard pages list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:page-details" pk=page.pk %}">
        <svg data-src="{% static "dashboard/images/chevron-left.svg" %}" />
      </a>
    </li>
    <li>
      <a href="{% url "dashboard:page-details" pk=page.pk %}" class="breadcrumbs--ellipsed-item">
        {{ page }}
      </a>
    </li>
    {% if translation.pk %}
      <li>
        <a href="{% url "dashboard:page-translation-details" pk=page.pk translation_pk=translation.pk %}" class="breadcrumbs--ellipsed-item">
          {{ translation }}
        </a>
      </li>
      <li>
      <span class="breadcrumbs--ellipsed-item">
        {% trans "Edit" context "translation form breadcrumbs" %}
      </span>
    </li>
    {% else %}
      <li>
        <span class="hide-on-med-and-down">
          {% trans "Add translation" context "translation form breadcrumbs" %}
        </span>
        <span class="hide-on-large-only breadcrumbs--ellipsed-item">
          {% blocktrans trimmed context "translation form breadcrumbs" %}
            Add translation for {{ page }}
          {% endblocktrans %}
        </span>
      </li>
    {% endif %}
  </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div class="col m12">
      <div class="card">
        <form method="post" id="form-translation" enctype="multipart/form-data">
          <div class="card-content">
            {% csrf_token %}
            <div class="row">
              <div class="col m12">
                <div class="row">
                  <b>{{ form.language_code|materializecss }}</b>
                </div>
                <div class="row">
                  {{ form.title|materializecss }}
                </div>
                <div class="row">
                  {{ form.content|materializecss }}
                </div>
                <div class="row">
                  {{ form.seo_title|materializecss }}
                </div>
                <div class="row">
                  {{ form.seo_description|materializecss }}
                </div>
              </div>
            </div>
          </div>
          <div class="card-action right-align">
            {% if translation.pk %}
              <a href="{% url "dashboard:page-details" pk=page.pk %}" class="btn-flat waves-effect">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect">
                {% trans "Save" context "Dashboard update action" %}
              </button>
            {% else %}
              <a href="{% url "dashboard:page-details" pk=page.pk %}" class="btn-flat waves-effect">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect">
                {% trans "Create" context "Dashboard create action" %}
              </button>
            {% endif %}
          </div>
        </form>
      </div>
    </div>
    <div class="col s12 m3 help-box"></div>
  </div>
{% endblock %}