saleor/dashboard/product/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',
        views.product_list, name='product-list'),
    url(r'^(?P<pk>[0-9]+)/$',
        views.product_details, name='product-details'),
    url(r'^(?P<pk>[0-9]+)/publish/$',
        views.product_toggle_is_published, name='product-publish'),
    url(r'^add/select-type/$',
        views.product_select_type, name='product-add-select-type'),
    url(r'^add/(?P<type_pk>[0-9]+)/$',
        views.product_create, name='product-add'),
    url(r'^(?P<pk>[0-9]+)/update/$',
        views.product_edit, name='product-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.product_delete, name='product-delete'),
    url(r'^bulk-update/$',
        views.product_bulk_update, name='product-bulk-update'),
    url(r'^ajax/products/$',
        views.ajax_products_list, name='ajax-products'),

    url(r'^types/$',
        views.product_type_list, name='product-type-list'),
    url(r'^types/add/$',
        views.product_type_create, name='product-type-add'),
    url(r'^types/(?P<pk>[0-9]+)/update/$',
        views.product_type_edit, name='product-type-update'),
    url(r'^types/(?P<pk>[0-9]+)/delete/$',
        views.product_type_delete, name='product-type-delete'),

    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/$',
        views.variant_details, name='variant-details'),
    url(r'^(?P<product_pk>[0-9]+)/variants/add/$',
        views.variant_create, name='variant-add'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/update/$',
        views.variant_edit, name='variant-update'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/delete/$',
        views.variant_delete, name='variant-delete'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/images/$',
        views.variant_images, name='variant-images'),
    url(r'^ajax/variants/$',
        views.ajax_available_variants_list, name='ajax-available-variants'),

    url(r'^(?P<product_pk>[0-9]+)/translations/(?P<translation_pk>[0-9]+)/$',
        views.translation_details, name='translation-details'),
    url(r'^(?P<product_pk>[0-9]+)/translation/$',
        views.translation_create, name='product-translation-add'),
    url(r'^(?P<product_pk>[0-9]+)/translation/add/$',
        views.translation_create, name='product-translation-add'),
    url(r'^(?P<product_pk>[0-9]+)/translations/(?P<translation_pk>[0-9]+)/update/$',
        views.translation_edit, name='translation-update'),
    url(r'^(?P<product_pk>[0-9]+)/translations/(?P<translation_pk>[0-9]+)/delete/$',
        views.translation_delete, name='translation-delete'),

    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/translations/(?P<translation_pk>[0-9]+)/$',
        views.variant_translation_details, name='variant-translation-details'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/translations/(?P<translation_pk>[0-9]+)/update/$',
        views.variant_translation_edit, name='variant-translation-update'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/translations/(?P<translation_pk>[0-9]+)/delete/$',
        views.variant_translation_delete, name='variant-translation-delete'),

    url(r'^(?P<product_pk>[0-9]+)/images/$',
        views.product_images, name='product-image-list'),
    url(r'^(?P<product_pk>[0-9]+)/images/add/$',
        views.product_image_create, name='product-image-add'),
    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/$',
        views.product_image_edit, name='product-image-update'),
    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/delete/$',
        views.product_image_delete, name='product-image-delete'),
    url(r'^(?P<product_pk>[0-9]+)/images/reorder/$',
        views.ajax_reorder_product_images, name='product-images-reorder'),
    url(r'^(?P<product_pk>[0-9]+)/images/upload/$',
        views.ajax_upload_image, name='product-images-upload'),

    url(r'attributes/$',
        views.attribute_list, name='attributes'),
    url(r'attributes/(?P<pk>[0-9]+)/$',
        views.attribute_details, name='attribute-details'),
    url(r'attributes/add/$',
        views.attribute_create, name='attribute-add'),
    url(r'attributes/(?P<pk>[0-9]+)/update/$',
        views.attribute_edit, name='attribute-update'),
    url(r'attributes/(?P<pk>[0-9]+)/delete/$',
        views.attribute_delete, name='attribute-delete'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/add/$',
        views.attribute_value_create,
        name='attribute-value-add'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/details/$',  # noqa
        views.attribute_value_details, name='attribute-value-details'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/update/$',  # noqa
        views.attribute_value_edit,
        name='attribute-value-update'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/delete/$',  # noqa
        views.attribute_value_delete,
        name='attribute-value-delete'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/values/reorder/$',
        views.ajax_reorder_attribute_values,
        name='attribute-values-reorder'),

    url(r'attributes/(?P<attribute_pk>[0-9]+)/translations/(?P<translation_pk>[0-9]+)$',
        views.attribute_translation_details, name='attribute-translation-details'),
    url(r'^add/attributes/translation/$',
        views.attribute_translation_create, name='attribute-translation-add'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/translation/add/$',
        views.attribute_translation_create, name='attribute-translation-add'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/translations/(?P<translation_pk>[0-9]+)/edit/$',
        views.attribute_translation_edit, name='attribute-translation-update'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/translations/(?P<translation_pk>[0-9]+)/delete/$',
        views.attribute_translation_delete, name='attribute-translation-delete'),

    url(r'^add/attributes/value/translation/$',
        views.attributevalue_translation_create, name='attributevalue-translation-add'),
    url(r'attributes/value/(?P<attvalue_pk>[0-9]+)/translation/add/$',
        views.attributevalue_translation_create, name='attributevalue-translation-add'),
    url(r'attributes/value/(?P<attvalue_pk>[0-9]+)/translation/(?P<translation_pk>[0-9]+)/edit/$',
        views.attributevalue_translation_edit, name='attributevalue-translation-edit'),
    url(r'attributes/value/(?P<attvalue_pk>[0-9]+)/translation/(?P<translation_pk>[0-9]+)/delete/$',
        views.attributevalue_translation_delete, name='attributevalue-translation-delete'),

    # temporary redirect to previous url after product saving
    url(r'^ajax-paged-url/$', views.ajax_paged_url, name='ajax-paged-url'),
    url(r'^return-to-paged-url/$', views.return_to_paged_url, name='return-to-paged-url'),
]

saleor/product/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<slug>[a-z0-9-_]+?)-(?P<product_id>[0-9]+)/$',
        views.product_details, name='details'),
    url(r'^category/(?P<slug>[a-z0-9-_]+?)-(?P<category_id>[0-9]+)/$',
        views.category_index, name='category'),
    url(r'(?P<slug>[a-z0-9-_]+?)-(?P<product_id>[0-9]+)/add/$',
        views.product_add_to_cart, name='add-to-cart'),
    url(r'^collection/(?P<slug>[a-z0-9-_/]+?)-(?P<pk>[0-9]+)/$',
        views.collection_index, name='collection'),

    url(r'^ajax-selected-variant/$', views.ajax_selected_variant, name='ajax-selected-variant'),
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import (
    cart_urlpatterns as cart_urls, checkout_urlpatterns as checkout_urls)
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.views import GraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

from django.views.generic import TemplateView

handler404 = 'saleor.core.views.handle_404'

non_translatable_urlpatterns = [
    url(r'^dashboard/',
        include((dashboard_urls, 'dashboard'), namespace='dashboard')),
    url(r'^graphql/', csrf_exempt(GraphQLView.as_view(
        schema=schema)), name='api'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^i18n/$', set_language, name='set_language'),
    url('', include('social_django.urls', namespace='social'))]

translatable_urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^cart/', include((cart_urls, 'cart'), namespace='cart')),
    url(r'^checkout/',
        include((checkout_urls, 'checkout'), namespace='checkout')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^order/', include((order_urls, 'order'), namespace='order')),
    url(r'^page/', include((page_urls, 'page'), namespace='page')),
    url(r'^products/',
        include((product_urls, 'product'), namespace='product')),
    url(r'^account/',
        include((account_urls, 'account'), namespace='account')),
    url(r'^feeds/',
        include((feed_urls, 'data_feeds'), namespace='data_feeds')),
    url(r'^search/', include((search_urls, 'search'), namespace='search'))]

urlpatterns = non_translatable_urlpatterns + i18n_patterns(
    *translatable_urlpatterns)

urlpatterns += [
    url(r'^robots\.txt$', TemplateView.as_view(template_name="robots/robots.txt", content_type='text/plain')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        # static files (images, css, javascript, etc.)
        url(r'^static/(?P<path>.*)$', serve)] + static(
            '/media/', document_root=settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [
        url(r'^silk/', include('silk.urls', namespace='silk'))]

saleor/product/forms.py
import json

from django import forms
from django.utils.encoding import smart_text
from django.utils.translation import pgettext_lazy
from django_prices.templatetags.prices_i18n import amount

from ..checkout.forms import AddToCartForm
from ..core.utils.taxes import display_gross_prices


class VariantChoiceField(forms.ModelChoiceField):
    discounts = None
    taxes = None
    display_gross = True

    def label_from_instance(self, obj):
        variant_label = smart_text(obj.translated.name)
        price = obj.get_price(self.discounts, self.taxes)
        price = price.gross if self.display_gross else price.net
        label = pgettext_lazy(
            'Variant choice field label',
            '%(variant_label)s - %(price)s') % {
                # 'variant_label': variant_label, 'price': amount(price)}
                'variant_label': variant_label, 'price': amount(price)}
        return label

    def update_field_data(self, variants, discounts, taxes):
        """Initialize variant picker metadata."""
        self.queryset = variants
        # print(self.queryset)
        self.discounts = discounts
        self.taxes = taxes
        self.empty_label = None
        self.display_gross = display_gross_prices()
        images_map = {
            variant.pk: [
                vi.image.image.url for vi in variant.variant_images.all()]
            for variant in variants.all()}
        self.widget.attrs['data-images'] = json.dumps(images_map)
        # Don't display select input if there is only one variant.
        if self.queryset.count() == 1:
            self.widget = forms.HiddenInput(
                {'value': variants.all()[0].pk})

class ProductForm(AddToCartForm):
    variant = VariantChoiceField(queryset=None)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        variant_field = self.fields['variant']
        variant_field.update_field_data(
            self.product.variants.all(), self.discounts, self.taxes)

    def get_variant(self, cleaned_data):
        return cleaned_data.get('variant')

templates/dashboard/product/product_translation/detail.html
{% extends "dashboard/base.html" %}

{% load i18n %}
{% load price from taxed_prices %}
{% load static %}
{% load status %}

{% block title %}
  {{ translation }} - {{ block.super }}
{% endblock %}

{% block body_class %}body-products{% endblock %}

{% block menu_products_class %}active{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:product-list" %}" class="breadcrumb">
        {% trans "Products" context "Product form breadcrumbs" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:product-list" %}">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li class="hide-on-med-and-down">
      <a href="{% url "dashboard:product-details" pk=product.pk %}" class="breadcrumbs--ellipsed-item">
        {{ product }}
      </a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {{ translation }}
      </span>
    </li>
  </ul>
{% endblock %}

{% block header_extra %}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col m12">
      <div class="card">
        <div class="card-content">
{#          <div style="overflow: auto; width: 100%; display: inline-block">#}
          <div>
          <table class="bordered responsive data-table">
            <tbody>
            <tr>
              <td><b>{% trans "Language" context "Dashboard action" %}</b></td>
              <td><b>{{ translation.language_code }}</b></td>
            </tr>
            <tr>
              <td>{% trans "Title" context "Dashboard action" %}</td>
              <td style="white-space: pre-wrap">{{ translation.name }}</td>
            </tr>
            <tr>
              <td>{% trans "Seo Title" context "Dashboard action" %}</td>
              <td style="white-space: pre-wrap">{{ translation.seo_title }}</td>
            </tr>
            <tr>
              <td>{% trans "Description" context "Dashboard action" %}</td>
              <td style="white-space: pre-wrap">{{ translation.description }}</td>
            </tr>
            <tr>
              <td>{% trans "Seo Description" context "Dashboard action" %}</td>
              <td style="white-space: pre-wrap">{{ translation.seo_description }}</td>
            </tr>
            </tbody>
          </table>
          </div>
        <div class="card-action">
          <a class="btn-flat waves-effect" href="{% url 'dashboard:translation-update' product_pk=product.pk translation_pk=translation.pk %}">
            {% trans "Edit" context "Dashboard action" %}
          </a>
          <a href="#base-modal" class="btn-flat waves-effect modal-trigger-custom" data-href="{% url 'dashboard:translation-delete' product_pk=product.pk translation_pk=translation.pk %}">
            {% trans "Remove" context "Dashboard action" %}
          </a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/dashboard/product/product_translation/form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load static %}

{% block title %}
  {% if translation.pk %}
    {% trans "Edit" context "translation form page title" %} - {{ translation }}
  {% else %}
    {% trans "Add translation" context "translation form page title" %}
  {% endif %}
   - {{ block.super }}
{% endblock %}

{% block body_class %}body-store body-products{% endblock %}

{% block header_menu %}
  {% url "dashboard:translation-details" product_pk=product.pk translation_pk=translation.pk as url %}
  {% include "dashboard/includes/_back_link.html" with url=url %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:product-list" %}" class="breadcrumb">
        {% trans "Products" context "Dashboard products list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:product-details" pk=product.pk %}">
        <svg data-src="{% static "dashboard/images/chevron-left.svg" %}" />
      </a>
    </li>
    <li>
      <a href="{% url "dashboard:product-details" pk=product.pk %}" class="breadcrumbs--ellipsed-item">
        {{ product }}
      </a>
    </li>
    {% if translation.pk %}
      <li>
        <a href="{% url "dashboard:translation-details" product_pk=product.pk translation_pk=translation.pk %}" class="breadcrumbs--ellipsed-item">
          {{ translation }}
        </a>
      </li>
      <li>
      <span class="breadcrumbs--ellipsed-item">
        {% trans "Edit" context "translation form breadcrumbs" %}
      </span>
    </li>
    {% else %}
      <li>
        <span class="hide-on-med-and-down">
          {% trans "Add translation" context "translation form breadcrumbs" %}
        </span>
        <span class="hide-on-large-only breadcrumbs--ellipsed-item">
          {% blocktrans trimmed context "translation form breadcrumbs" %}
            Add translation for {{ product }}
          {% endblocktrans %}
        </span>
      </li>
    {% endif %}
  </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div class="col m12">
      <div class="card">
        <form method="post" id="form-translation" enctype="multipart/form-data">
          <div class="card-content">
            {% csrf_token %}
            <div class="row">
              <div class="col m12">
                <div class="row">
                  <b>{{ form.language_code|materializecss }}</b>
                </div>
                <div class="row">
                  {{ form.name|materializecss }}
                </div>
                <div class="row">
                  {{ form.description|materializecss }}
                </div>
                <div class="row">
                  {{ form.seo_title|materializecss }}
                </div>
                <div class="row">
                  {{ form.seo_description|materializecss }}
                </div>
              </div>
            </div>
          </div>
          <div class="card-action right-align">
            {% if translation.pk %}
              <a href="{% url "dashboard:translation-details" product_pk=product.pk translation_pk=translation.pk %}" class="btn-flat waves-effect">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect">
                {% trans "Save" context "Dashboard update action" %}
              </button>
            {% else %}
              <a href="{% url "dashboard:product-details" pk=product.pk %}" class="btn-flat waves-effect">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect">
                {% trans "Create" context "Dashboard create action" %}
              </button>
            {% endif %}
          </div>
        </form>
      </div>
    </div>
    <div class="col s12 m3 help-box"></div>
  </div>
{% endblock %}